### ISSUE TITLE
Missing .pfx-file

### ISSUE THREAD

**Issue by haakoo** [jchristn/SimpleTcp#1]
I'm hoping to use this little library and cloned the repo and tried to build it. During build in VS 2016.1.2 I get an error about missing `.pfx`-file in both the `TestNetFramework`-projects.

I couldn't see anything in the _Readme_ about this. Did you forget to commit the file (it's in the `.gitignore`-file), or is it intentional?

I guess I could create it again with the command in the `certificate-instructions.txt` file.

**Comment by jchristn** [comment]
Hello and thanks for your note!  I’ll check the .gitignore today and get it fixed!

Thank you for bringing this to my attention and sorry for this slowing you down :)

**Comment by jchristn** [comment]
Hi @haakoo this should be fixed now.  Cheers!
