### ISSUE TITLE
Support for domains

### ISSUE THREAD

**Issue by OpNop** [jchristn/SimpleTcp#11]
I think a good addition to this would be to add support for domains. 

I'm currently dong
```csharp
if (!IPAddress.TryParse(serverAddr, out IPAddress ipAddress))
{
    ipAddress = Dns.GetHostEntry(serverAddr).AddressList[0];
}
client = new TcpClient(ipAddress.ToString(), serverPort, false, null, null)
```
but might make sense to move that logic into the library maybe?

Thanks

**Comment by jchristn** [comment]
Hi @OpNop - is the use case on this to automatically determine the server address on which to listen?

**Comment by OpNop** [comment]
no, this is on the client side, im my example, the app has a default server address of chat.domain.com but accepts a user provided server from the command line. But I could see it just being useful to use a domain in the client and is also supported by the normal TcpClient supports hostname normally 
`public TcpClient (string hostname, int port);`
https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.-ctor?view=netframework-4.8#System_Net_Sockets_TcpClient__ctor_System_String_System_Int32_

but in your code you are forcing an IP address at https://github.com/jchristn/SimpleTcp/blob/master/SimpleTcp/TcpClient.cs#L160

Hope that makes sense :)

**Comment by jchristn** [comment]
Hi @OpNop thanks for the clarification, this is an excellent suggestion and I'll move it into the library right now!

**Comment by jchristn** [comment]
Integrated!  Thanks again for the suggestion, @OpNop !

NuGet: https://www.nuget.org/packages/SuperSimpleTcp/2.0.2
Commit: https://github.com/jchristn/SimpleTcp/commit/54826eff6a249926cd7503a0248b7d407e4ea4ad
