### ISSUE TITLE
[Question] Handle reconnect

### ISSUE THREAD

**Issue by OpNop** [jchristn/SimpleTcp#12]
Hello again. What is the proper way to do a reconnect with your library? I currently have the following 

```csharp
private void ServerDisconnected(object sender, EventArgs e)
{
    WriteToChat("Server disconnected, Retrying in 5 seconds");
    new Thread(TryReconnect).Start();
}

private void TryReconnect()
{
    Thread.Sleep(5000);
    while (!client.IsConnected)
    {
        client.Connect();
        Thread.Sleep(5000);
    }
}
```

But I'm getting the error
`System.Net.Sockets.SocketException: 'A connect request was made on an already connected socket'` 
This topic [HERE](https://www.codeproject.com/Questions/1187207/A-connect-request-was-made-on-an-already-connected) talks about setting the socket as reusable and disconnecting the socket on the client side, but I don't see a disconnect option in the `TcpClient` or options to set it as reusable

Thanks again

**Comment by jchristn** [comment]
Hi @OpNop try reinstantiating the entire client object inside your TryReconnect method ie client = new TcpClient(... and attaching your callbacks in there. Once it’s disconnected the TcpClient object has to be reinstantiated. 

I’ll be back at my computer tomorrow night and can provide more detail. Sorry I’m mobile right now (which explains the less than thorough answer!).

**Comment by jchristn** [comment]
Hi @OpNop did this help solve the issue for you?  Sorry I was out of town.  Cheers, Joel

**Comment by OpNop** [comment]
No problem, yes I ended up writing this, feels a bit messy, but works
```csharp
private void ConnectToServer(bool reconnect = false)
{
    //Dispose of old connection if reconnecting
    if (reconnect)
        client.Dispose();

    _log.AddInfo($"Connecting to {serverAddr}:{serverPort}");
    client = new TcpClient(serverAddr, serverPort, false, null, null);
    client.Connected += ServerConnected;
    client.Disconnected += ServerDisconnected;
    client.DataReceived += MessageReceived;
    try
    {
        client.Connect();
    }
    catch (Exception)
    {
        WriteToChat("Can not connect to server, retrying in 5 seconds");
        if(!reconnect) new Thread(TryReconnect).Start();
    }
}

private void ServerDisconnected(object sender, EventArgs e)
{
    WriteToChat("Server disconnected, Retrying in 5 seconds.");
    new Thread(TryReconnect).Start();
}

private void TryReconnect()
{
    while (!client.IsConnected)
    {
        Thread.Sleep(5000);
        ConnectToServer(true);
    }
}
```

**Comment by jchristn** [comment]
Glad it works.  I'd love to build reconnect logic into the objects themselves but it isn't as clean as I would like.  Perhaps in a future version.  Cheers!
