### ISSUE TITLE
Allow client to connect to an IpPort, instead of specifying IP and Port

### ISSUE THREAD

**Issue by matt1tk** [jchristn/SimpleTcp#17]
Is there a way to connect directly to an IpPort, instead of separately specifying each of them? This is because the server saves it as args.IpPort instead of separate IP and port. Alternatively can the server save them separately? :)

**Comment by jchristn** [comment]
Hi @matt1tk please let me know if this works (please re-open if it doesn't).  Thanks!

Commit: https://github.com/jchristn/SimpleTcp/commit/cb6e4267734892b6f8ed6f63769105d65e75d235
NuGet: https://www.nuget.org/packages/SuperSimpleTcp/2.0.6.1

**Comment by matt1tk** [comment]
Worked for me, thanks!
