### ISSUE TITLE
Feature Request - IdleClientTimeoutSeconds

### ISSUE THREAD

**Issue by pha3z** [jchristn/SimpleTcp#2]
Would like to see IdleClientTimeoutSeconds added to Simple TcpServer.

I'd mark this as an enhancement, but I don't know how to add labels or that kind of thing on Github. I googled for it briefly but couldn't find a straight forward explanation.

**Comment by jchristn** [comment]
Here you go, please let me know if any issues.

NuGet: https://www.nuget.org/packages/SuperSimpleTcp/1.1.5
Commit: https://github.com/jchristn/SimpleTcp/commit/1125a3acf5dde8c84912561d885ecbdd108bbcf2

Cheers, Joel
