### ISSUE TITLE
Always times out

### ISSUE THREAD

**Issue by Fischchen** [jchristn/SimpleTcp#20]
Hey it´s me again,

Now im having the issue that when i try to connect to the TCP server i just  time out:
```
System.TimeoutException
  HResult=0x80131505
  Nachricht = Timeout connecting to (IP Adress)
  Quelle = SimpleTcp
  Stapelüberwachung:
   at SimpleTcp.SimpleTcpClient.Connect()
```
The server is running with Mono on a RPI Zero W
Please help me!

Greetings,
Fischchen

**Comment by jchristn** [comment]
Hi @Fischchen can you post your TCP client constructor code all the way from ```new SimpleTcpClient(...``` to ```.Connect()```?

From your RPI, can you telnet to the server port successfully?

**Comment by Fischchen** [comment]
Here you go:
```
  public SimpleTcpServer server;

    public TCP_Server(int port)
    {
        server = new SimpleTcpServer("127.0.0.1", port, false, null, null);
        server.Events.ClientConnected += ClientConnected;
        server.Events.ClientDisconnected += ClientDisconnected;
        server.Events.DataReceived += DataReceived;
        server.Keepalive.EnableTcpKeepAlives = false;
        server.Start();
    }
```

**Comment by Fischchen** [comment]
here is the Client:

```
private SimpleTcpClient client;

        public TCP_Client(string ip, int port)
        {
            client = new SimpleTcpClient(ip, port, false, null, null);
            client.Events.Connected += Connected;
            client.Events.Disconnected += Disconnected;
             client.Keepalive.EnableTcpKeepAlives = false;
            client.Settings.ConnectTimeoutSeconds = 60;
            client.Connect();
        }
```

**Comment by jchristn** [comment]
Thanks - are client and server both on the same machine?

**Comment by Fischchen** [comment]
no one the Server on linux with open firewall and the client on my Windows pc

**Comment by jchristn** [comment]
Got it.  If you want to expose the port to the outside, you have to listen on something other than ```127.0.0.1```.  You can listen on a specific interface IP address, or, ```*``` to listen on all IP addresses.  Note that you may have run as root/administrator (this is an OS limitation, not a SimpleTcp limitation) in some cases.  

If you listen on ```127.0.0.1``` you can only accept connections from the local machine.

I'll update the README with this - looks like I have it on WatsonTcp but not SimpleTcp.

Let me know if that works for you!

**Comment by Fischchen** [comment]
oh thanks! I´ll try that out

**Comment by Fischchen** [comment]
Thanks a lot it works now!!!!

**Comment by Fischchen** [comment]
Thanks a lot it work now!

**Comment by Fischchen** [comment]
Hey i just tried to conntect to the server via the Public IP and i timed out again.
Please help me!

**Comment by Job79** [comment]
Try starting the server on ‘0.0.0.0‘ instead, ‘*‘ does not work on some linux distro's.

Does the server work when trying to connect to the internal ip of the pi? (assuming you use the same 
network as the pi, type ‘ip a‘ in a shell) If yes then your router is probably blocking the connection. Try port forwarding it again.

**Comment by Fischchen** [comment]
i tried 0.0.0.0 and it´s still not working. When i use the internal ip it work but i need to use the External later

**Comment by jchristn** [comment]
Are you running as root?  

I assume you have NAT on a router in front of it. Is it configured to forward to your device IP and port?

**Comment by Fischchen** [comment]
Well thats akward! I forgot to run it as root...

Sorry for everybody i anoyed

**Comment by jchristn** [comment]
All good 😊

**Comment by Fischchen** [comment]
Since you guys seem to know a lot about mono can a ask a off-topic question?

**Comment by jchristn** [comment]
I only know a little bit but please feel free

**Comment by Fischchen** [comment]
When i start my pogramm with root all file and directory.create command just dont get executet

**Comment by Fischchen** [comment]
i dont know if im stupid or if that a security feature

**Comment by jchristn** [comment]
That's an interesting one.  Maybe put some debug statements in before to see what your working directory is?  I don't know, but perhaps when running as root it's using a different working directory.

I would assume root *should* have filesystem permissions everywhere.  If not you may want to try to add them.

**Comment by Job79** [comment]
Are you sure the file's aren't created somewhere else? (the homedir('~') changes when running as root)

I assume you are using a port < 1024? These are privileged ports and can't be used without root permissions, but all other ports are free.
If possible switch to a higher port, this would allow your application to run without root permissions.

**Comment by jchristn** [comment]
@Job79 he'd have to supply a specific IP instead of a wildcard though, correct?  I believe root/admin is required for wildcard.

**Comment by Fischchen** [comment]
thanks a lot

**Comment by Job79** [comment]
> @Job79 he'd have to supply a specific IP instead of a wildcard though, correct? I believe root/admin is required for wildcard.

Ports > 1024 work fine when used by a non-root, everything below 1024 throws a `System.Net.Sockets.SocketException (5): Permission denied`
Tested with dotnet core and linux 5.8.10-arch with `0.0.0.0` as ip.

**Comment by jchristn** [comment]
Good to know, thanks!
