### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by singsong2016** [jchristn/SimpleTcp#21]
when i copy the demo in readme.md to run,   here occur err:   
	// once a client has connected...
	server.Send("[ClientIp:Port]", Encoding.UTF8.GetString("Hello, world!"));  //cannot convert from 'string' to 'byte[]'

this state should be:
      server.Send("[ClientIp:Port]", "Hello, world!");

**Comment by Fischchen** [comment]
It has to be 
`Encoding.UTF8.GetBytes("Hello, world!")`

**Comment by jchristn** [comment]
Which version are you using?

![image](https://user-images.githubusercontent.com/1421081/93892803-c697e900-fca1-11ea-8239-ee690b5b80ea.png)

**Comment by singsong2016** [comment]
Net framework 461





------------------ Original ------------------

**Comment by jchristn** [comment]
Hi @singsong2016 how about the version of the NuGet package?

**Comment by jchristn** [comment]
Cancel that, I see the issue. My apologies. It should be fine in the README now just using strings. I see now that I had GetString instead of GetBytes. Thank you!

**Comment by jchristn** [comment]
README now has examples using the string variants of ```Send```.  Thank you everyone for pointing this out!

![image](https://user-images.githubusercontent.com/1421081/93897556-10cf9900-fca7-11ea-8cb9-cd5fd3ee8ff5.png)

and
![image](https://user-images.githubusercontent.com/1421081/93897579-188f3d80-fca7-11ea-8255-6effe8c560ce.png)
