### ISSUE TITLE
Stop listening?

### ISSUE THREAD

**Issue by Antwns** [jchristn/SimpleTcp#22]
Hello! How can I make the server stop listening for X amount of seconds or permanently without a .dispose();?
Thanks in advance!
EDIT: Server MUST not be disposed at any point in the code.

**Comment by jchristn** [comment]
Hi @Antwns could you give this a try and let me know if any issues?

NuGet: https://www.nuget.org/packages/SuperSimpleTcp/2.1.0.4
Commit: https://github.com/jchristn/SimpleTcp/commit/5b26e499fcf8e003fb65a94e3d6b22000ce9c8a2

**Comment by Antwns** [comment]
Hello! The new .Strop(); Command works perfectly!!! Thank you so much! 😄

**Comment by jchristn** [comment]
Awesome :)  Enjoy!
