### ISSUE TITLE
Create a Websockets Server?

### ISSUE THREAD

**Issue by pha3z** [jchristn/SimpleTcp#25]
Hey Joel, your vast experience and knowledge has been really helpful in the past so I'm asking about this rather than going down a rabbit hole of failed experiments first!

So far I have not been able to find a simple C# websocket Server library that is cross-platform, future-proof, and lightweight. 

Lightweight websocket libs have historically depended on httpListener, but httpListener was deprecated. It looks like Microsoft has pretty much abandoned lightweight http support in favor of bigger full-framework solutions like Kestrel + ASP.

I found this:
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_server

It uses TcpListener and shows you how to receive a GET request and escalate to a websocket connection.  I haven't tried it yet.  I notice its extremely barebones and almost looks "too easy"??  It's clearly not going to have the bells and whistles of a full http listener, but I probably don't even need that.

The purpose of my investigation is to build a c# application that uses websockets for IPC connection to a webview frontend.  I want to maintain UI state within the c# application and do very minimal lifting inside the webview.  The webview would only have some javascript to establish a websocket connection to the c# application.  The webview javascript would have some utility functions for DOM manipulation and event binding, but all of that would be driven from within the C# app where the state can be tracked.

I've seen some other developers looking for solutions like this, and many of them don't know where to look.  There is so much over-engineered junk that depends on Asp.net, razor, blazor, electron, or other alphabet soup libraries.

The nice thing about the approach I want to build is that you could make it work within almost any framework. It could be used with Electron easily, but you could also use it with native webviews and windows.  Ideally, it would be usable on Android and iOS _which is one of the reasons I ended up looking at TcpListener and doing a low-level implementation of websockets that would work on both Mono and .NET Core 5 and be somewhat future proof._

What are your thoughts on this?
Does the Mozilla example doc I linked oversimplify the needs of a simple one-client/localhost-server scenario?
Is there a lightweight mono and .net core compatible websocket server lib somewhere that I just haven't come across yet?

If nothing exists, would it make sense to try to use SimpleTcp to be the foundation for a cross-plat websocket server?

Looking forward to your thoughts!!!  Thanks for your time in advance!!

**Comment by pha3z** [comment]
Oh my goodness.  I just noticed you already have this:
https://github.com/jchristn/WatsonWebsocket

Amazing!!

**Comment by jchristn** [comment]
Hi @pha3z good to hear from you!  WatsonWebsocket works pretty well but is dependent on http.sys. 

I have another project called HttpServerLite that is a TcpListener-based HTTP server. I have intentions of using that to gut the internals of WatsonWebsocket and get rid of http.sys for the reasons you describe. 

Cheers :)

**Comment by jchristn** [comment]
Closing as the enhancement is open on WatsonWebsocket
