### ISSUE TITLE
Combine both web socket server and client

### ISSUE THREAD

**Issue by zydjohnHotmail** [jchristn/SimpleTcp#26]
Hello:
I have one special request, I need some help.
I need some kind of web socket relay program.  I have one very fast web socket data source, the server is not in my control.  But the external web socket server generates huge amount of text data, I can write one web socket client to receive the huge amount of data, but less than 10% of the data is needed.  As the external web socket server generates too much data, my web socket client is always freeze, yet less than 10% of the data is useful.
I want to write a web socket relay program, which is one web socket client for the external web socket server, but at the same time, acts as one internal web socket server, send only those 10% useful data to another web socket client.
Another web socket client can process all the useful data. In this design, the web socket relay program will be busy to process all the web socket data, but another web socket client will not be freeze to process only 10% of total data received.
Let me know if my thinking is practical, if yes, can you provide some code example.
Thanks,

**Comment by jchristn** [comment]
Hi @zydjohnHotmail I'm not sure how to respond.  SimpleTcp is a TCP client and server, not a websocket client or websocket server.   You should look into using a websocket library for this, where you have an intermediary piece of software acting as both client and server; it would be the server to the client that needs the useful data, and the client to the server that is emitting that data.  I have a websocket library called WatsonWebsocket that you could check out; it includes both a websocket client and a websocket server, and you could build such a system.  https://github.com/jchristn/WatsonWebsocket
