### ISSUE TITLE
[Question] How to keep the connection for a client forever?

### ISSUE THREAD

**Issue by xCruziX** [jchristn/SimpleTcp#29]
Hello, 

I'm using the client example, but as soon as the server sends a message to the client, I get an exception.
I commented out the code in while (_RunForever) and replace Console. with Debug. because this is a winform application.
Everytime my Server send a message it throws the exception.

![image](https://user-images.githubusercontent.com/59866158/100268688-a44a7200-2f55-11eb-9421-60dc422eca90.png)

I'm new to c# and network programming, so ty for any help.

**Comment by jchristn** [comment]
Hi @xCruziX are you instantiating the client and server inside of a form or are you instantiating in the global context?

What exception are you encountering?

**Comment by xCruziX** [comment]
Just for testing I calling only the method Main from the client example in my winform project.
The exception, the first line is the message from server on another maschine:
`[127.0.0.1:8588] {"id":1606331811624,"typ":1,"msg":"test"}
Ausnahme ausgelöst: "System.Net.Sockets.SocketException" in SimpleTcp.dll
Ausnahme ausgelöst: "System.Net.Sockets.SocketException" in mscorlib.dll
[SimpleTcp.Client] data receiver canceled, peer disconnected`

**Comment by jchristn** [comment]
That makes sense.  It's likely being disposed.  Are you switching forms?  Having the client or server instantiated inside the form creates problems with garbage collection disposing them.

**Comment by xCruziX** [comment]
This is my structure:
I have made a winform application and removed the creation of the Form object.
At this time, in the main method i am just calling the static method from the client example in your repo.

![image](https://user-images.githubusercontent.com/59866158/100273407-ffcc2e00-2f5c-11eb-9504-43c287caa87b.png)

![image](https://user-images.githubusercontent.com/59866158/100273415-03f84b80-2f5d-11eb-9441-b3ff168e6192.png)

**Comment by xCruziX** [comment]
I wonder why it works but just until the first message comes in

**Comment by jchristn** [comment]
Do the client test and server test work when you run them standalone, i.e. not integrated into your app?

In the model you're showing here, how are you starting the server?

**Comment by xCruziX** [comment]
Ok, I just tried to start the Client from your Projekt, nothing changed except the Port and I geht the same exception.

Ausnahme ausgelöst: "System.Net.Sockets.SocketException" in SimpleTcp.dll
Ausnahme ausgelöst: "System.Net.Sockets.SocketException" in System.Private.CoreLib.dll


![image](https://user-images.githubusercontent.com/59866158/100278693-956bbb80-2f65-11eb-999a-6133fdf06ecd.png)

**Comment by jchristn** [comment]
Can you send the server side too?

**Comment by xCruziX** [comment]
Yes, I could send the Server side tomorrow, but its in nodejs with net modules.

https://nodejs.org/api/net.html

**Comment by jchristn** [comment]
Ah, no need to send that. 

Does the client remain connected when you run the ClientTest and ServerTest projects directly?

**Comment by xCruziX** [comment]
Ok, with the ServerTest is works.. but how I can fix this problem for my nodejs application?
I've used this as pattern:
https://gist.github.com/sid24rane/2b10b8f4b2f814bd0851d861d3515a10

**Comment by jchristn** [comment]
Hi @xCruziX I'm afraid I won't be able to help with that one right now, there must be something in your connection loop that is closing after sending the first message.  Let's leave it open to see if anyone else wants to comment.
