### ISSUE TITLE
[Question] Unnecessary loop at SimpleTcpClient 

### ISSUE THREAD

**Issue by MaynardSi** [jchristn/SimpleTcp#30]
Hello, I am learning socket programming. I would like to ask why is there an infinite ` while (true)` loop at line 577 of the `SimpleTcpClient `class after awaiting the read, writing into the MemoryStream, and converting to an array? Since the read array is returned immediately after the conversion, the loop would not iterate.

```csharp
     private async Task<byte[]> DataReadAsync(CancellationToken token)
        {  
            byte[] buffer = new byte[_Settings.StreamBufferSize];
            int read = 0;

            if (!_Ssl)
            { 
                using (MemoryStream ms = new MemoryStream())
                {
                    while (true)
                    {
                        read = await _NetworkStream.ReadAsync(buffer, 0, buffer.Length, token).ConfigureAwait(false);

                        if (read > 0)
                        {
                            await ms.WriteAsync(buffer, 0, read, token).ConfigureAwait(false);
                            return ms.ToArray();
                        }
                        else
                        {
                            throw new SocketException();
                        }
                    }
                } 
            }
```

**Comment by jchristn** [comment]
Hi @MaynardSi good catch, there doesn't need to be :)  This is a remnant from another project; I'll remove it.  Thanks!

**Comment by jchristn** [comment]
Thanks again @MaynardSi :)

NuGet: https://www.nuget.org/packages/SuperSimpleTcp/2.1.0.13
Commit: https://github.com/jchristn/SimpleTcp/commit/27776467c623c2b1a2ae01337c92f6d0e5acbdc2
