### ISSUE TITLE
Connecting to multiple servers from one computer

### ISSUE THREAD

**Issue by saklanmazozgur** [jchristn/SimpleTcp#31]
Hello, I will connect to multiple servers from one computer. I should save the data I received from these servers to the list after a mathematical process.

Is there any way to know the server with which ip address the data is coming from?

// In this way, I can find out which one is triggered, but properties such as ip address and port come as non-static properties.
`private void EthernetDataReceived(object sender, DataReceivedFromServerEventArgs e)
{
	SimpleTcpClient client = (SimpleTcpClient)sender;       
}`

Also, is it right to use only one EthernetDataReceived for each server?

`client.Events.DataReceived += EthernetDataReceived;`

Is there an example of multi connection? If available, can you share?

**Comment by jchristn** [comment]
Hi there @saklanmazozgur your use case is one I had not thought of; having multiple instances of SimpleTcpClient connecting to different servers, but sharing the same event handlers.  

Right now the server information isn't exposed as public in the SimpleTcpClient, nor is it exposed in the event args.

Let me amend the event args so that you get the server information with it.  Stay tuned.  And thank you for bringing this up!

**Comment by jchristn** [comment]
Hi @saklanmazozgur please try v2.2.0, just posted to NuGet.  

Please use the ```DataReceivedEventArgs``` instead of the previous ```DataReceivedFrom(Server|Client)EventArgs```.  

The ```IpPort``` property is there for both client and server.

Please re-open if this doesn't solve the issue.  Thanks for making the library better!

NuGet: https://www.nuget.org/packages/SuperSimpleTcp/2.2.0
Commit: https://github.com/jchristn/SimpleTcp/commit/3d6dfcc381193ddc2d81281aee685d317588095b

**Comment by saklanmazozgur** [comment]
Perfect speed. Thank you so much. I will try it at my project workplace tomorrow morning and come back. Thank you again.

**Comment by asenyurt** [comment]
> Please use the DataReceivedEventArgs instead of the previous DataReceivedFrom(Server|Client)EventArgs.

could you pls write this information to first page change log ??

**Comment by jchristn** [comment]
Hi @asenyurt I did add it to the README as well as the CHANGELOG.  Is there another place where I should post?

Cheers, Joel

![image](https://user-images.githubusercontent.com/1421081/101680625-93eec880-3a26-11eb-9be0-45a329a8f618.png)

**Comment by saklanmazozgur** [comment]
Hello @jchristn , I still can't access Ip and Porta even though I have updated the package. My code is as follows, what's the problem? 
IpPort feature still seems to be not visible.

`selectedclient = (SimpleTcpClient)sender;
            var ipPort = selectedclient.IpPort;`

**Comment by jchristn** [comment]
Hi @saklanmazozgur the IP/port are not exposed in the client object, but rather in the ```DataReceived``` event arguments, i.e. ```DataReceivedEventArgs```:
```csharp
static void DataReceived(object sender, DataReceivedEventArgs e)
{
  Console.WriteLine("[" + e.IpPort + "] " + Encoding.UTF8.GetString(e.Data));
}
```

**Comment by saklanmazozgur** [comment]
Sorry, Sorry, my fault there is no problem. Thank you.

**Comment by jchristn** [comment]
No worries my friend, have a good one!

**Comment by saklanmazozgur** [comment]
I want to add a little detail. The return value of IpPort is IpAddress + Port. There are no signs such as ":" to distinguish between the two. This can sometimes cause problems.

For Example; Ip Address : 192.168.1.23  Port : 23


The returned value is "192.168.1.2323". In this case, there are multiple options.

Maybe IpAddress : 192.168.1.23 Port : 23 

Maybe IpAddress : 192.268.1.232 Port : 3

Maybe IpAddress : 192.168.1.2  Port : 323


It's ok for me now but it can be fixed for future change.

**Comment by jchristn** [comment]
Ah, I will look at it tomorrow morning. Not sure how I missed that. 

I'll also expose IpPort off of the client itself too. 

Cheers, Joel

**Comment by jchristn** [comment]
Should be fixed in v2.2.0.1 (https://www.nuget.org/packages/SuperSimpleTcp/2.2.0.1), commit is here (https://github.com/jchristn/SimpleTcp/commit/502b8913feb96a3843d1e307f5659ba6121af821).

I've also:
- Exposed ```ServerIpPort``` from the ```SimpleTcpClient``` object
- Updated the README with more details on the breaking changes

**Comment by saklanmazozgur** [comment]
Thank you so much. You fixed the problems very quickly.

Should I open a separate title?

Now I can do it myself in different ways. But in order to be better, the system that keeps the data from different ip in separate lists and can control these lists can be very useful in case of multiple connections.

It makes data management easy. For example; I've created two links 192.168.1.20:23 and 192.168.1.21:23. Writing the data from here to a list called 192.168.1.21 as soon as it arrives and checking this list can increase efficiency.

I don't know if this is necessary or unnecessary.

**Comment by jchristn** [comment]
Hi @saklanmazozgur not sure I understand what you're asking here, could you ask it a different way?

**Comment by saklanmazozgur** [comment]
Hi @jchristn ,


Now, in my project, I have to write the data from different ipaddresses into separate lists. I am having a problem in how I will record in what order. 

The number of connections can be 500. The user can close and open connections as they wish. In case he closes the connection, no registration should be made for that list.


For example; The ip address 192.168.1.20 - 192.168.1.30 - 192.168.1.40 is three connections. I know from which ip address the data comes from but I cannot control which list I should write the data to.


I have 3 lists named Log_1 Log_2 Log_3. In case of opening the connection, I can record respectively. When he closes the 2nd connection and then reconnects, the queue will be shifted and this will make my administration difficult. How can I get out of this situation?

**Comment by jchristn** [comment]
You could always use a ```ConcurrentDictionary<string, Queue>```.  https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?view=net-5.0

The key for the dictionary would be the ```IpPort``` of the sender, and the value would be a queue of data specifically from that sender.  i.e. in your server's ```DataReceived``` event, add the data to the queue using the client's IpPort as the dictionary key.  When a client connects, initialize the queue and add it to the dictionary.  When a client disconnects, remove the queue from the dictionary (or force it all to be processed).

**Comment by saklanmazozgur** [comment]
Thanks, this seems to work for me. I tried and failed. The problem is that FullData.TryAdd (Key, TValue) in EthernetDataReceived; When I do, it adds once for each key and then it does not add.

When the first data arrives, it adds up and then does not. How can I solve this problem. I'm new and I don't know some things. Please don't be sorry.

**Comment by saklanmazozgur** [comment]
I fixed problem. Thank you for helps.

`ConcurrentDictionary<string, Queue<byte[]>> FullData = new ConcurrentDictionary<string, Queue<byte[]>>();`

DataReceived Code

`var queue = FullData.GetOrAdd(e.IpPort, (key) => new Queue<byte[]>());
            queue.Enqueue(Data);`

**Comment by AdemKinatas** [comment]
@saklanmazozgur hocam selamlar yukarıda belirttiğin kodlar multi server kullanımı için mi?

**Comment by saklanmaz** [comment]
@AdemKinatas burada türkçe konuşmak doğru olmayabilir saklanmazozgur@gmail.com adresine mail atarsan yardımcı olabilirim. (It may not be correct to speak Turkish here, if you send an e-mail to sakmazozgur@gmail.com, I can help.)

**Comment by AdemKinatas** [comment]
@saklanmazozgur ok thanks for your answer.I send email to your mail address
