### ISSUE TITLE
Error when server starting from different pc

### ISSUE THREAD

**Issue by asenyurt** [jchristn/SimpleTcp#33]
Hello

I got error when i try to open software from different pc.
Its working in visual studio pc but when i press to start button i got error like this:
![image](https://user-images.githubusercontent.com/73142096/101823425-63488500-3b33-11eb-82f6-d4f9aa851d0f.png)

**Comment by jchristn** [comment]
Hi @asenyurt may I see the code?

**Comment by asenyurt** [comment]
![image](https://user-images.githubusercontent.com/73142096/101823730-e2d65400-3b33-11eb-8061-ff57c0aec65c.png)

**Comment by jchristn** [comment]
The IP address you are supplying, does it appear in your list of IP addresses when running the command ```ipconfig```?

**Comment by asenyurt** [comment]
Yes. same ip on running pc

**Comment by jchristn** [comment]
Interesting.  What version of the library are you using?  

Do you experience the same issue when using the ```ServerTest``` project?

Example below where I use the ```IP:port``` constructor and am listening on an IP address that is in the ```ipconfig``` list.

![image](https://user-images.githubusercontent.com/1421081/101830272-1f309280-3ae9-11eb-8fc5-a4e1a1a04fd9.png)

**Comment by asenyurt** [comment]
is it possible to write me your mail ??
so i can send full of code you can try.

interesting thing, i dont get any error when i try with visual studio installed pc..

**Comment by jchristn** [comment]
Sure thing, it's joel dot christner at gmail

**Comment by asenyurt** [comment]
i send it

**Comment by jchristn** [comment]
Resolved offline, cheers
