### ISSUE TITLE
client.Connect () freezes the interface.

### ISSUE THREAD

**Issue by saklanmazozgur** [jchristn/SimpleTcp#34]
If a connection cannot be established to the ip address entered by the user, `ethernet.Connect (); `command freezes the interface for about 5 seconds.

Could the reason be that EthernetConnect runs on the same thread as the ui? How can I fix the problem.

**Comment by jchristn** [comment]
Hi @saklanmazozgur yes, if you have any socket logic in your UI thread, that will create problems.  I recommend that you  instantiate the object outside of your UI.

**Comment by saklanmazozgur** [comment]
Hi @jchristn ,
Thank you. I fixed the problem.

**Comment by jchristn** [comment]
Awesome, I'm glad to hear @saklanmazozgur !!
