### ISSUE TITLE
Server not starting.

### ISSUE THREAD

**Issue by BarrettTorqueEm** [jchristn/SimpleTcp#35]
Upon starting basic project I am unable to connect to the started server. (see code below) When scanning my open ports, it is not listed (see screenshot attached), although if I start a TcpListener as shown in the code (commented) it does. I also tested with your given examples to no avail. 

`    static void Main(string[] args) {
        // TcpListener s = new TcpListener(63534);
        // s.Start();
        server = new SimpleTcpServer("127.0.0.1", 63534);

        server.Events.ClientConnected += Server_ClientConnected;
        server.Events.DataReceived += Server_DataRecieved;
        server.Events.ClientDisconnected += Server_ClientDisconnected;
        server.Logger += Logger;

        Start();
        Console.WriteLine(server.IsListening);
        Console.ReadLine();
    }`

<img width="1370" alt="Screen Shot 2020-12-17 at 10 51 52 PM" src="https://user-images.githubusercontent.com/27873549/102572566-779ffb00-40ba-11eb-90f4-7e31c1cc9a8d.png">

**Comment by jchristn** [comment]
Could you show me the contents of the ```Start()``` method?

**Comment by BarrettTorqueEm** [comment]
Joel,

My apologies I thought I moved the `Start()` method. See below just a writeline and start.

I am using net5.0 and macOS BigSur. I have a windows 10 machine I can test with tomorrow afternoon EST.

`private static void Start() {
        Console.WriteLine("Starting server...");
        server.Start();
    }
`

Thanks, Mike

**Comment by jchristn** [comment]
Thanks Mike - ouch, that's interesting.  The test I ran above was using .NET 5, but it was on Windows (I don't have a Mac machine nearby).  I'll see if I can get one tomorrow to test on this side also.  Do you get any exceptions or anything when ```server.Start()``` is called?  Does the ```Console.WriteLine(server.IsListening);``` report ```true```?

**Comment by BarrettTorqueEm** [comment]
I receive no issues ether to the integrated terminal (VSCode) or by the Logger event. (Using a `Console.WriteLine`). The `Console.WriteLine(server.IsListening);` does report `true`. -Mike

**Comment by jchristn** [comment]
Hi @BarrettTorqueEm I just tried in .NET 5 on Catalina and am having issues too.  I also tried in netcoreapp3.1 and it's having issues.  Wanted to let you know I was digging into this and will report back once I find something.

**Comment by BarrettTorqueEm** [comment]
Thanks for the update! -Mike

**Comment by jchristn** [comment]
I've been struggling with a weird exception message.  Have tested using 127.0.0.1, localhost, 0.0.0.0/*/+, and the adapter IP. 
 The exception message I keep getting is ```Connection refused [::ffff:127.0.0.1]:9000```.  The IP portion of that string obviously seems like IPv6 commingled with IPv4.  Firewall is disabled.  Still digging.

**Comment by jchristn** [comment]
Ok, I got it to work.

**Disable TCP keepalives on both client and server**

I'm not sure why this is the case, but there are definitely weird things happening with TCP keepalives across various operating systems.

On the server:
```csharp
server.Keepalive.EnableTcpKeepAlives = false;
```
On the client:
```csharp
client.Keepalive.EnableTcpKeepAlives = false;
```

I'll keep digging, but please confirm whether this does/doesn't work for you.

**Comment by jchristn** [comment]
Hi @BarrettTorqueEm I wanted to let you know I did some additional testing (see this repo: https://github.com/jchristn/KeepaliveTest) and found that there are definitely differences between .NET 5.0 and .NET Core 3.1 in terms of the impact/implications of enabling TCP keepalives.  

The highlight reel is this: 
- .NET Core 3.1 works fine with or without keepalives on either client or server
- .NET 5.0 works great with or without keepalives on the client, but enabling keepalives on the server precludes the listener from accepting connections.

I've filed an issue with MS on this.  In the meantime, I recommend either disabling server-side TCP keepalives, or, using .NET Core 3.1 if you need them.  

https://github.com/dotnet/core/issues/5773

I'll keep this open while I wait to hear back from MS on this.

Cheers, Joel

**Comment by BarrettTorqueEm** [comment]
Thank you very much for all your help Im mearly using this package to test my understanding of Client/server programing. Im not using it in any PROD instance. Have a good one. -Mike

**Comment by jchristn** [comment]
Thanks again @BarrettTorqueEm just a heads-up I disabled TCP keepalives by default in v2.2.1, which I just pushed/commited.  Cheers
