### ISSUE TITLE
Does SimpleTcp support auto-reconnection?

### ISSUE THREAD

**Issue by EricaCode** [jchristn/SimpleTcp#36]
I haven't used this project to realize my functions so far but I'd like to know whether SimpleTcp support auto-reconnection or not.

**Comment by jchristn** [comment]
Hi @EricaCode it does not from within the library, however, you can embed reconnection logic into ```SimpleTcpClient.Events.Disconnected```.
```
static void Disconnected(object sender, ClientDisconnectedEventArgs e)
{
    while (!client.IsConnected)
    {
        client.Connect();
    }
}
```
(you'd want to handle exceptions in there, too)
