### ISSUE TITLE
Always times out

### ISSUE THREAD

**Issue by xXjojaXx** [jchristn/SimpleTcp#38]
My Client cant connect to my Server. The client is on another pc in the same wlan network. I added permit rules for the port 9000 for in and out on both pcs and checked if they allow tcp connections.
This is my code for the client:
[Client.txt](https://github.com/jchristn/SimpleTcp/files/5899891/Client.txt)

This is my code of the server:
[Server.txt](https://github.com/jchristn/SimpleTcp/files/5899893/Server.txt)

I started the server with the ip: 0.0.0.0 and the client with the ip copied from the ipconfig of the server. I deactivated my virusdetections and started the server with administrator privileges. The timeout is configured to be 60 seconds.
I always get the following error: "Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeit nicht richtig reagiert hat, oder die Verbindung fehlerhaft war, da der verbundene Host nicht reagiert hat. [ip-adress of server:9000].

If i connect with the client on the same pc it works completly fine.

**Comment by Fischchen** [comment]
Da du ein deutschen Fehler hast schreiben ich mal auf deutsch:
Erlaubt dein Router portforwarding? Die port weiterleitung muss für dein Server Port aktiviert sein, sonst funkoniert es nicht.

**Comment by xXjojaXx** [comment]
Mir war nicht bewusst das du Deutsch bist ;) wie kann ich das für meinen Router herausfinden?

**Comment by Fischchen** [comment]
See error #20

**Comment by jchristn** [comment]
Hi @xXjojaXx tganks for your note. If it is connecting successfully on the same machine it means the server is working and listening. 

If connections timeout from remote machines it means something in between the machines is stopping the connection, usually a router, firewall, NAT configuration. 

If they are on the same subnet I'd start with the machine firewall. 

Cheers, Joel

PS (sorry I do not speak German, otherwise I would have replied in German to you) :-)

**Comment by jchristn** [comment]
Also which operating system are you using for client and server, and which runtime?

**Comment by Fischchen** [comment]
> Mir war nicht bewusst das du Deutsch bist ;) wie kann ich das für meinen Router herausfinden? 

Auf diesem Link ist eine Liste, du musst nur dein Router auswählen und die Werbung ignorieren:
https://portforward.com/router.htm

**Comment by jchristn** [comment]
Were you able to get it working?

**Comment by jchristn** [comment]
Please re-open if more assistance is needed.  Cheers
