### ISSUE TITLE
Client disconnects after some time if he is not in the same network

### ISSUE THREAD

**Issue by w123u567** [jchristn/SimpleTcp#41]
If I use my program in a local network (same PC or PCs in the same network) it works without any problems.
But when I connect from a PC in another network the PC/Client disconnects after some time (sometimes after a few second and sometimes after 1-2 minutes). The program runs (correctly) into the disconnected event handler and if I debug the sender object (the SimpleTcpClient object) the received and sent bytes are always about 50-60 bytes.

Code to start the server:

```
_server = new SimpleTcpServer("0.0.0.0", Convert.ToInt32(tb_Port.Text));

_server.Keepalive.EnableTcpKeepAlives = true;
_server.Keepalive.TcpKeepAliveInterval = 10;
_server.Keepalive.TcpKeepAliveTime = 10;
_server.Keepalive.TcpKeepAliveRetryCount = 10;

_server.Events.ClientConnected += Events_ClientConnected;
_server.Events.ClientDisconnected += Events_ClientDisconnected;
_server.Events.DataReceived += Events_DataReceived;

_server.Start();
```

Code to connect the client:

```
_client = new SimpleTcpClient(tb_serverIP.Text, Convert.ToInt32(tb_port.Text));

_client.Keepalive.EnableTcpKeepAlives = true;
_client.Keepalive.TcpKeepAliveInterval = 10;
_client.Keepalive.TcpKeepAliveTime = 10;
_client.Keepalive.TcpKeepAliveRetryCount = 10;

_client.Events.Connected += Events_Connected;
_client.Events.Disconnected += Events_Disconnected;
_client.Events.DataReceived += Events_DataReceived;

_client.Connect();
```

What can I try to fix this issue?

**Comment by jchristn** [comment]
Hi, you may have to build a method that periodically sends a heartbeat message.  I haven't found TCP keepalives to be completely reliable on all platforms, especially when there may be intermediary devices.

What OS are you using for client and server?  Which framework/runtime are you using?

**Comment by w123u567** [comment]
> Hi, you may have to build a method that periodically sends a heartbeat message. I haven't found TCP keepalives to be completely reliable on all platforms, especially when there may be intermediary devices.
> 
> What OS are you using for client and server? Which framework/runtime are you using?

I'm using Windows for server and client. The Server is a Windows Forms App (.Net Framework 4.7.2), the Client is a WPF Application (also .Net Framework 4.7.2)

**Comment by w123u567** [comment]
How often should this heartbeat method been called? I have a method on server that send all 50ms data to all clients and also a method on client site that sends all 50ms data to the server (if something changed)

**Comment by jchristn** [comment]
Hi @w123u567 I would start with something around 10 seconds.  An alternative would be to use Wireshark on the client and server and see if a TCP reset is being sent from one side to the other, or from an intermediary device.  Cheers, Joel

**Comment by w123u567** [comment]
Thank you, I will try this.

**Comment by w123u567** [comment]
Wireshark shows the following output:
![image](https://user-images.githubusercontent.com/78880823/107590745-3d119500-6c09-11eb-94ee-0aabd5bd62dc.png)

It seems like the server sends a TCP reset to the client, but I don't understand why.

**Comment by w123u567** [comment]
I also implemented a method that sends every few seconds data (on client and on server), but nothing changed.

**Comment by jchristn** [comment]
Could you try setting ```_server.Keepalive.EnableTcpKeepAlives = false;``` and the same thing on the client, and see what happens?  All of the TCP keepalive functionality is buried within the kernel - the properties I provide simply set them using the exposed APIs, and anecdotally, they aren't the most reliable.

**Comment by jchristn** [comment]
Also the 'spurious retransmissions' may be of concern - it indicates that Wireshark has already seen the ACK, but perhaps the ACK was not received by the sender.  

Are your client and server on the same LAN segment, i.e. there's no router in between them (other than perhaps a WiFi router)?

https://www.chappell-university.com/post/spurious-retransmissions-a-concern

**Comment by w123u567** [comment]
> Could you try setting `_server.Keepalive.EnableTcpKeepAlives = false;` and the same thing on the client, and see what happens? All of the TCP keepalive functionality is buried within the kernel - the properties I provide simply set them using the exposed APIs, and anecdotally, they aren't the most reliable.

I tried this and at the moment it's running since a few minutes without disconnecting. Maybe this was the solution. Also no 'spurious retransmissions' are shown in WireShark.

**Comment by jchristn** [comment]
Got it.  Well, let's hope that fixes the issue for you!  I was tempted to leave TCP keepalives out of all of my TCP libraries since it's really like dark voodoo magic that happens under the hood, and no controls/notifications are provided when the kernel takes action.  Would you mind keeping me updated on how it looks after some time?  Cheers, Joel

**Comment by w123u567** [comment]
> Also the 'spurious retransmissions' may be of concern - it indicates that Wireshark has already seen the ACK, but perhaps the ACK was not received by the sender.
> 
> Are your client and server on the same LAN segment, i.e. there's no router in between them (other than perhaps a WiFi router)?
> 
> https://www.chappell-university.com/post/spurious-retransmissions-a-concern

If I use the client in the same Network everything was fine, only if I connect from outside of my private network (port forwarding is set correctly)

**Comment by w123u567** [comment]
> Got it. Well, let's hope that fixes the issue for you! I was tempted to leave TCP keepalives out of all of my TCP libraries since it's really like dark voodoo magic that happens under the hood, and no controls/notifications are provided when the kernel takes action. Would you mind keeping me updated on how it looks after some time? Cheers, Joel

Yes, I hope it will work now. I will do some tests and let you know if the problem is fixed. Thank you very much for the support :) 👍

**Comment by w123u567** [comment]
No more unwanted disconnects since I set `_server.Keepalive.EnableTcpKeepAlives = false;`. I will close this issue and hope for the best :)
