### ISSUE TITLE
ConnectTimeoutSeconds not working as expected

### ISSUE THREAD

**Issue by Exergist** [jchristn/SimpleTcp#44]
If a client cannot connect to a server a `SocketException` (ConnectionRefused) is thrown within 2 seconds of initiating the connection process regardless of the `ConnectTimeoutSeconds` value.  

```csharp
public void TimedConnect()
{
	client.Settings.ConnectTimeoutSeconds = 60;
	try
	{
		client.Connect();
	}
	catch (Exception ex)
	{
                MessageBox.Show(ex.Message, "Message", MessageBoxButtons.OK, MessageBoxIcon.Error);
	}
}
```
Basically `client.Settings.ConnectTimeoutSeconds = 60;` doesn't seem to be honored in the above example.

Please see relevant [discussion ](https://github.com/jchristn/SimpleTcp/discussions/42)for additional information.

**Comment by jchristn** [comment]
Hi @Exergist just a quick heads-up, I'm going to be implementing in the next few days.  Internally, two tasks will be started within ```Connect```: 1) a task that runs for ```Settings.ConnectTimeoutSeconds```, and the other, 2) a loop that continually tries to connect.  If the connect attempt in (2) is successful, both tasks will end, and the connect will be considered successful.  I'm also going to make an async variant.  Stay tuned and sorry for the delay.

**Comment by Exergist** [comment]
You're a champ, no rush AT ALL :)

**Comment by jchristn** [comment]
Hi @Exergist so it turns out ```ConnectTimeoutSeconds``` was actually working, but the expected result was not.  Thus I left ```Connect``` alone, and added another method ```ConnectWithRetries``` in v2.3.0 which produces the desired result.

Example 1, ```client.ConnectWithRetries(10)``` with the server offline the entire time.
```
C:\Code\Misc\SuperSimpleTcp-2.2>clienttest\bin\debug\net5.0\client
Server IP   : [127.0.0.1]
Server Port : [9000]
[SimpleTcp.Client] initializing client
[SimpleTcp.Client] connecting to 127.0.0.1:9000
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000 (1 retries)
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000 (2 retries)
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000 (3 retries)
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000 (4 retries)
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000 (5 retries)
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000 (6 retries)
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000 (7 retries)
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000 (8 retries)
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000 (9 retries)
Unhandled exception. System.TimeoutException: Timeout connecting to 127.0.0.1:9000
   at SimpleTcp.SimpleTcpClient.ConnectWithRetries(Nullable`1 timeoutSeconds) in C:\Code\Misc\SuperSimpleTcp-2.2\SimpleTcp\SimpleTcpClient.cs:line 395
   at ClientTest.Program.Main(String[] args) in C:\Code\Misc\SuperSimpleTcp-2.2\ClientTest\Client.cs:line 49
```

Example 2 is the same as example 1, but I turn the server on half way through so the connection can go through.
```
C:\Code\Misc\SuperSimpleTcp-2.2>clienttest\bin\debug\net5.0\client
Server IP   : [127.0.0.1]
Server Port : [9000]
[SimpleTcp.Client] initializing client
[SimpleTcp.Client] connecting to 127.0.0.1:9000
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000 (1 retries)
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000 (2 retries)
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000 (3 retries)
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000 (4 retries)
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000 (5 retries)
[SimpleTcp.Client] connected to 127.0.0.1:9000
*** Server connected
```

v2.3.0 is committed (https://github.com/jchristn/SimpleTcp/commit/ac1c713fdbd9084bf0c4246ad7e2d102a945a50d) and live on NuGet (https://www.nuget.org/packages/SuperSimpleTcp/2.3.0).  Please re-open if any issues.  Thanks!
