### ISSUE TITLE
How to avoid graphics refresh in newly opened window?

### ISSUE THREAD

**Issue by saklanmazozgur** [jchristn/SimpleTcp#50]
Hello, 

I have a graph with a home screen. I want to open this chart in new window. I can open the chart in a new window, but as data comes to the chart on the home page, the data in the window I just opened is refreshed.

If I don't click on the chart, the renewal doesn't occur. When I click on any point of the graph with the mouse, it prints the data on the main screen.

How can I prevent this? The code I use to open in a new window is as follows.

```
var AxisX_Copy = HpsvAxisX_Graphic.plt.Copy();
AxisX_Copy.Ticks(dateTimeX: true, dateTimeFormatStringX: ("HH.mm.ss"));
AxisX_New_Window = new WpfPlotViewer(AxisX_Copy);
AxisX_New_Window.Show();
```

**Comment by jchristn** [comment]
Wrong library.

**Comment by saklanmazozgur** [comment]
Sorry my fault. Sorry for the waste of time.
