### ISSUE TITLE
asynchronous get responses

### ISSUE THREAD

**Issue by laomms** [jchristn/SimpleTcp#56]
This is some piece of code from https://github.com/Phyyl/ObooltNet/blob/master/Source/ObooltNet/NetConnection.cs  
Is it possible to add SendAndWait function to SimpleTcp ?
SimpleTcp is more stable and  powerful.

```
        private void CheckServerUsedAsClient()
        {
            if (listener != null)
            {
                throw new InvalidOperationException("Cannot use a server connection as a client");
            }
        }

        private void CallOnDataReceived(TcpClients connection, byte[] data)
        {
            if (OnDataReceived != null)
                OnDataReceived(this, connection, data);
        }

        private async Task<byte[]> ReceiveFromAsync( int timeout = 5000)
        {
            try
            {
                _Client.ReceiveTimeout = timeout;
                NetworkStream stream = _Client.GetStream();
                byte[] buffer = new byte[8193];
                MemoryStream ms = new MemoryStream();
                int bytesRead = 0;
                while (_Client.Connected)
                {
                    if (bytesRead > 0)
                    {
                        return buffer.Take(bytesRead).ToArray();
                    }
                    bytesRead = await stream.ReadAsync(buffer, 0, buffer.Length);
                    ms.Write(buffer, 0, bytesRead);
                    if (!stream.DataAvailable)
                    {
                        CallOnDataReceived(_Client, ms.ToArray());
                        ms.Seek(0, SeekOrigin.Begin);
                        ms.SetLength(0);
                    }
                }
            }
            catch
            {

            }
            return null;
        }

        public async Task<byte[]> SendAndReceiveData(byte[] data, int timeout = 5000)
        {
            CheckServerUsedAsClient();
            _Client.GetStream().Write(data, 0, data.Length);
            var tskReceive = await ReceiveFromAsync( timeout);
            return tskReceive;
        }

        public byte[] SendAndWait(byte[] Data, int timeout = 5000)
        {
            Task<byte[]> testTask = SendAndReceiveData(Data, timeout);
            testTask.Wait();
            return testTask.Result;
        }

        //private async Task<bool> AwaitTimeoutTask(Task task, int timeout)
        //{
        //    return await Task.WhenAny(task, Task.Delay(timeout)) == task;
        //}
```

**Comment by jchristn** [comment]
Hi @laomms there are a few reasons why I'm hesitant to do it.

1) Without any kind of framing, you have no confirmation that the response you receive is actually for the request you sent.  This is a problem in anything multi-threaded or in cases where you have multiple outstanding requests.

2) The methods are above are not thread-safe.  You could potentially have multiple readers attempting to get data from the socket.

3) Related to 2, SimpleTcp has a single background task continually reading from the socket.  No read APIs are exposed via the library, but rather, an event that is fired when data is received.  

If you need request-response sync patterns I have them built into WatsonTcp (https://github.com/jchristn/watsontcp) which does implement a framing mechanism.  If you need low-level control over both read and write operations, I also have another library called CavemanTcp (https://github.com/jchristn/cavemantcp) which allows you to specify a) that you want to read and b) how many bytes you want to read.  

Another danger in blindly reading a large amount of data (i.e. in the code above, setting the buffer to 8KB) is that if you have multiple messages sitting in the socket receive buffer, you're going to read them all out at once.

Hope this helps - as much as I'd love to do it in SimpleTcp, it's just not the right architecture for it.

Cheers, Joel

**Comment by laomms** [comment]
ok, thanks
