### ISSUE TITLE
IsConnected variable not changed

### ISSUE THREAD

**Issue by u1035** [jchristn/SimpleTcp#57]
Hello!
I'm trying to use this library as client, and have a small issue.

I'm connecting to server with code like this:
```
_client = new SimpleTcpClient(host, port);
_client.Logger = Logger;
_client.Events.DataReceived += Events_MessageReceived;
_client.Events.Connected += Events_ServerConnected;
_client.Events.Disconnected += Events_ServerDisconnected;
_client.Connect();
```

And first thing I need to do - is send "handshake" to server (server is not mine).
I do it in Events_ServerConnected() callback, but _client.Send() fails with exception "Not connected to the server; use Connect() first.".

I debugged inside SimpleTcp code, and found that it checks _IsConnected variable, and throws exception when it's false.
But seems that nobody sets _IsConnected to true...
I tried to add _IsConnected = true; to end of both Connect() and ConnectWithRetries() before event calling,
and it started working.

**Comment by vlOd2** [comment]
I have the same issue as well. When I try to Send() it fails and trows and exception.

Also question how did you set IsConnected to true because it's a read only variable?

**Comment by u1035** [comment]
> Also question how did you set IsConnected to true because it's a read only variable?

I downloaded SimpleTcp project sources, and added them to my solution instead of NuGet package - so I was able to walk with debugger inside it and make changes.

**Comment by vlOd2** [comment]
Thanks! I completly forgot about that. Because I tried dnSpy and it didn't work.

**Comment by jchristn** [comment]
Thank you @u1035 for the PR, this is now in NuGet as v2.3.0.1.  I appreciate you doing this!

NuGet: https://www.nuget.org/packages/SuperSimpleTcp/2.3.0.1
Commit: https://github.com/jchristn/SimpleTcp/commit/08861e30727c4deaeceabe8529c4eafb4bd03cb0
