### ISSUE TITLE
IdleClientDisconnect appears to be broken

### ISSUE THREAD

**Issue by pha3z** [jchristn/SimpleTcp#6]
I haven't had a chance to create a minimum test scenario. I apologize, I've been swamped. But I Imagine this will be pretty easy to track down.

I set the IdleClientTimeoutSeconds property when I create a TcpServer instance and get the following result:
A client connects.
The TimeoutSeconds time passes.
The server reports that the client disconnected... Reason: Timeout.

It behaves as if data received from the client is not resetting the timeout timer (which is probably exactly what the bug is).

- James

**Comment by jchristn** [comment]
Hi @pha3z - ouch!  Thanks for letting me know.  I was able to reproduce, looking at it now.  Cheers

**Comment by jchristn** [comment]
Hi @pha3z thanks for finding this, just published a fix!

NuGet: https://www.nuget.org/packages/SuperSimpleTcp/1.1.7
Commit: https://github.com/jchristn/SimpleTcp/commit/6d3e8345d8d03e5050f37420ed6ad6cdb8211306

**Comment by pha3z** [comment]
Its fixed!  Thank you!!! :)
