### ISSUE TITLE
ConnectWithRetries generates multiple connections from a single client instance

### ISSUE THREAD

**Issue by Exergist** [jchristn/SimpleTcp#60]
If I perform the following I get multiple client connections between one client instance and one server instance:

1. Create client instance
2. Initiate client connection (attempt) via `ConnectWithRetries`
3. Wait a few seconds (something less than value given to `ConnectWithRetries`)
4. Create server instance
5. Initiate server listening via `Start`

Here are the results for my simple client-server example:
![image](https://user-images.githubusercontent.com/31357974/110198070-5d51ff80-7e15-11eb-806a-5f689c7ff8ca.png)
As you can see there are seemingly TWO client connections with the server, even though the intent was to have only ONE client connection. If I start the server prior to initiating a client connection via `ConnectWithRetries`, there is only ONE client connection made as expected. 

For reference here is my code for initiating a client connection with the server:
```csharp
private void btnConnect_Click(object sender, EventArgs e)
{
	try
	{
		client.ConnectWithRetries(10);
		btnConnect.Enabled = false;
	}
	catch(Exception ex)
	{
		MessageBox.Show(ex.Message, "Message", MessageBoxButtons.OK, MessageBoxIcon.Error);
		btnConnect.Enabled = true;
	}
}
```

... and here is my code for updating the server UI after making a client connection:

```csharp
private void Events_ClientConnected(object sender, ClientConnectedEventArgs e)
{
	this.Invoke((MethodInvoker)delegate
	{
		txtInfo.Text += $"{e.IpPort} connected.{Environment.NewLine}";
		lstClientIP.Items.Add(e.IpPort);
		btnSend.Enabled = true;
		btnDisconnect.Enabled = true;
	});
}
```

**Is this behavior expected?**

**Comment by jchristn** [comment]
Hi @Exergist definitely not the behavior.  I was able to reproduce, looking into it now.
![image](https://user-images.githubusercontent.com/1421081/110224485-d5114000-7e90-11eb-9a9d-8df9d270b584.png)

**Comment by jchristn** [comment]
Getting ready to publish a fix.  Thanks for letting me know!
![image](https://user-images.githubusercontent.com/1421081/110224509-2e796f00-7e91-11eb-8b8e-e75c522a33d9.png)

**Comment by jchristn** [comment]
NuGet: https://www.nuget.org/packages/SuperSimpleTcp/2.3.0.2
Commit: https://github.com/jchristn/SimpleTcp/commit/44dc230fdb142d2d20817b74465530c25334bace

Please re-open if any issues.  Cheers @Exergist
