### ISSUE TITLE
IsConnected doesn't seem to be updating on disconnect

### ISSUE THREAD

**Issue by OpNop** [jchristn/SimpleTcp#7]
I might be doing something wrong, or there is a race condition going on but I have a check right before I send a packet to `client.IsConnected` but when the server disconnects it still shows `IsConnected` as true and the packet fails because its been disconnected 

![IsConnected](https://user-images.githubusercontent.com/14283547/74600187-1008c180-504b-11ea-8efc-4505d93cb03b.PNG)

Thanks

**Comment by jchristn** [comment]
Hi @OpNop - thanks - I just reproduced this.  Looking now.

**Comment by jchristn** [comment]
Try this and let me know if it resolves the issue?

Commit: https://github.com/jchristn/SimpleTcp/commit/db6ef1f8f6dea17c911a4777685f1b31acce4ccc

NuGet v1.1.8: https://www.nuget.org/packages/SuperSimpleTcp/1.1.8 (may take 5-10 mins to become available)

**Comment by OpNop** [comment]
Looks Good! thanks for fixing it so fast.

**Comment by jchristn** [comment]
My pleasure.  Thanks!
