### ISSUE TITLE
Connected event of client does not fire.

### ISSUE THREAD

**Issue by TalicZealot** [jchristn/SimpleTcp#72]
# Version
2.4.0 Nuget
# Description
The Connected event of the client does not seem to fire. Everything else works just fine. I can use the server's response to achieve what I want, but figured I might as well post about my issue here.
# Source
[https://github.com/TalicZealot/SotnRandoTools/blob/main/SotnRandoTools/src/Coop/CoopMessanger.cs](https://github.com/TalicZealot/SotnRandoTools/blob/main/SotnRandoTools/src/Coop/CoopMessanger.cs)

**Comment by jchristn** [comment]
Hi @TalicZealot do you see the same behavior using the ```ClientTest``` and ```ServerTest``` projects?  You should see the selected line in the screenshot below from those projects.
![image](https://user-images.githubusercontent.com/1421081/114896364-203e3d00-9dc5-11eb-946f-135f37750e76.png)

Does your ```Connect``` method return ```true```?

**Comment by TalicZealot** [comment]
I'm getting the same desired result as you with the test projects. At first I thought my event arguments had a mismatch, but I tried both variants with the same result.

**Comment by jchristn** [comment]
Does your ```Connect``` method return ```true```?

**Comment by TalicZealot** [comment]
I've refactored that method to be void. We have verified that a connection does get established and we can send and receive data without issues for extended periods of time, this is the one event that for some reason doesn't happen. I'm not using Keepalive since it causes stability issues, but from what I've read that doesn't have anything to do with this library. Since it works in the test project I feel like I missed something small and simple.

**Comment by jchristn** [comment]
Could you try adding ```client.Logger = Console.WriteLine``` into your ```Connect``` method?  Then check to see what (if any) messages appear?

```
public bool Connect(string hostIp, int port)
{
	if (client is null)
	{
		client = new SimpleTcpClient(hostIp, port);
	}

	try
	{
		client.ConnectWithRetries(4 * 1000);
	}
	catch (Exception)
	{
		Console.WriteLine("Connection timed out.");
		return false;
	}

	client.Events.DataReceived += DataReceived;
	client.Events.Connected += Connected;
	client.Events.Disconnected += Disconnected;
	client.Logger = Console.WriteLine;

	return true;
}
```

**Comment by TalicZealot** [comment]
![image](https://user-images.githubusercontent.com/18632109/114907774-1992e280-9e24-11eb-9e61-9e09caad21d8.png)
Received log messages on disconnecting. None on establishing a connection, sending or receiving data.

**Comment by jchristn** [comment]
Interesting - ```disconnecting from``` should also show the IP:port.  Something is disposing the client.  Is this a forms app?  If so you should consider defining your TCP client/server outside of the form, perhaps in ```app.cs``` as globals.

**Comment by TalicZealot** [comment]
Sorry I should have clarified that I erased the IP from the picture. It did show it. I disposed it manually by disconnecting. My project is a win forms extension to another win forms project.

**Comment by jchristn** [comment]
Interesting, give me a moment.  Thanks for clarifying.

**Comment by jchristn** [comment]
Does this line get evaluated correctly in your ```Connected``` event handler, i.e. do you see this variable gets populated correctly?
```
toolConfig.Coop.DefaultServer = client.ServerIpPort;
```

**Comment by TalicZealot** [comment]
It does not.

**Comment by jchristn** [comment]
Can you try commenting out your console writeline in the connect event handler and see if that variable gets set?

**Comment by TalicZealot** [comment]
No change in behavior. I also tried telling it to dispose the client in the Connected event to no avail.

**Comment by jchristn** [comment]
Got it.  But messages are able to be exchanged bidirectionally?

**Comment by TalicZealot** [comment]
Do you mean data? If so yes, everything works both ways. While I'm here there is something else that popped up recently. I'm disposing the client when it disconnects, but when the user reconnects and the server sends data it gets received twice.

**Comment by jchristn** [comment]
For disconnects, don't dispose.  If you dispose and then reconnect, you have to first re-instantiate the object.

I think I know why it's not working for you.  You're setting the ```Connected``` event AFTER calling ```ConnectWithRetries```.

Change it to this:
```
public bool Connect(string hostIp, int port)
{
	if (client is null)
	{
		client = new SimpleTcpClient(hostIp, port);
		client.Events.DataReceived += DataReceived;
		client.Events.Connected += Connected;
		client.Events.Disconnected += Disconnected;
	}

	try
	{
		client.ConnectWithRetries(4 * 1000);
	}
	catch (Exception)
	{
		Console.WriteLine("Connection timed out.");
		return false;
	}

	return true;
}
```

**Comment by TalicZealot** [comment]
Gonna try that now, I think using the Console.WriteLine at the top of the events can lock the thread and cause weird things to happen because it gets redirected to BizHawk's windows forms log window.

**Comment by TalicZealot** [comment]
Everything works perfectly now, no double data and the Connected event is firing. Than you so much for your time!

**Comment by jchristn** [comment]
Happy to help @TalicZealot
