### ISSUE TITLE
TcpClient.Connect throws NullReferenceException if called again after timeout

### ISSUE THREAD

**Issue by cmeeren** [jchristn/SimpleTcp#8]
I need to try to connect repeatedly until successful. I instantiate `TcpClient`, set `Connected`, `Disconnected`, and `DataReceived`, and then call `client.Connect()`. If an exception is raised while connecting, I try again. However, if the first `Connect` call throws `TimeoutException`, the next calls to `Connect` will throw `NullReferenceException`.

I assume the reason is that SimpleTcp disposes the client after timeout:

https://github.com/jchristn/SimpleTcp/blob/db6ef1f8f6dea17c911a4777685f1b31acce4ccc/SimpleTcp/TcpClient.cs#L202

**Comment by jchristn** [comment]
Hi @cmeeren are you reinitializing the ```TcpClient``` inside your connection loop?

**Comment by cmeeren** [comment]
No, I just call `Connect` again. What do you mean by "reinitialize"? The only thing I can think of is disposing/throwing away the old instance and newing up a completely new TcpClient.

**Comment by jchristn** [comment]
Yes, try reinitializing the TcpClient object.

**Comment by cmeeren** [comment]
Sorry, I'm confused - are you talking about newing up another TcpClient? Yes, that works, but is there any good reason it's required? Could TcpClient be changed to support reconnection after errors?

**Comment by jchristn** [comment]
Yes, I'm referring to creating a new instance of ```TcpClient```.  It could be amended to support such a case where reconnect could be performed, but it wasn't designed that way, and it would be an enhancement.

**Comment by cmeeren** [comment]
Gotcha, thanks!
