### ISSUE TITLE
write an timeout

### ISSUE THREAD

**Issue by heislpeda** [jchristn/SimpleTcp#86]
hey, how can i write an timeout if the server doesnt send any data after 10 seconds, i tried everything but nothing worked :/

` private void timer1_Tick(object sender, EventArgs e)
        {
            if(eldisCLIENT.IsConnected == false)
            {
                eldisCLIENT.ConnectWithRetries(10);
                MessageBox.Show("no data.");
            }
        }`

**Comment by jchristn** [comment]
Hi @heislpeda - moving this to discussions.
