### ISSUE TITLE
Use events instead of callbacks

### ISSUE THREAD

**Issue by cmeeren** [jchristn/SimpleTcp#9]
Is there any reason why this library is using `Func` callbacks instead of events? Events would be the idiomatic .NET tool for this job, and give a more pleasant dev experience.

Is it perhaps related to the callbacks returning `Task`, and that SimpleTcp must for some reason await callback completion? If so, why?

**Comment by jchristn** [comment]
Hi @cmeeren yes, a very simple explanation.  My familiarity :)  I'll look into migrating to Events in the next major release.  Cheers!

**Comment by jchristn** [comment]
Reopening to allow you to close when you feel it is working to your satisfaction.

**Comment by cmeeren** [comment]
Works great, thanks! 👍

**Comment by jchristn** [comment]
Thanks @cmeeren I really appreciate the time and effort you put into the pull request.  Now I have a few other libraries that I need to also convert from Func to Event...  Cheers :)
