### ISSUE TITLE
Project naming

### ISSUE THREAD

**Issue by tinohager** [jchristn/SimpleTcp#90]
Thanks for the great project I like to use your library.
I keep getting confused with the project name. Is there a reason why the project on Nuget is called [`SuperSimpleTcp`](https://www.nuget.org/packages/SuperSimpleTcp/) but on Nuget everything is described with `SimpleTcp`? It is also very irritating because on Nuget there is another package called [`SimpleTcp`](https://www.nuget.org/packages/SimpleTCP/) but nothing to do with this package.
Did you know that you can simply rename the project on Github and it will automatically redirect from the old name.

**Comment by jchristn** [comment]
Hi @tinohager thank you for your kind words.  Yes I'm aware of the other project, and the only reason I named mine "SuperSimpleTcp" was because the other was taken :)  You're right I should rename the repo.  I will do that now.  Hope you have a great week.  Cheers, Joel
